services:
  backend:
    build: ./Backend
    ports:
      - "8000:8000"
    volumes:
      - ./Backend:/Backend
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - DEBUG=1
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    env_file:
      - Backend/.env
    networks:
      - back_net
  database:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - database_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=prisma
    networks:
      - back_net
  ollama:
    image: ollama/ollama
    ports:
      - 11434:11434
    networks:
      - back_net

volumes:
  database_data:

networks:
  back_net:
