services:
  frontend:
    build: ./Frontend
    ports:
      - "5173:${FRONTEND_PORT}"
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - front_net

  backend:
    build: ./Backend
    ports:
      - "8000:${BACKEND_PORT}"
    volumes:
      - ./Backend:/Backend
      - ./.env.docker:/.env.docker
      - ./Backend/.env.secrets:/Backend/.env.secrets
    runtime: nvidia
    depends_on:
      - ollama
      - mongo_db
      - chromadb
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - DEBUG=1
      - OLLAMA_HOST=${OLLAMA_HOST}
      - OLLAMA_PORT=${OLLAMA_PORT}
    networks:
      - back_net
      - front_net
    restart: unless-stopped

  chromadb:
    image: chromadb/chroma
    ports:
      - "8002:8000"
    volumes:
      - chroma_data:/data
    networks:
      - back_net
    restart: unless-stopped

  ollama:
    image: ollama/ollama
    ports:
      - 8001:${OLLAMA_PORT}
    volumes:
      - ollama_data:/root/.ollama
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - back_net
    restart: unless-stopped

  mongo_db:
    image: mongodb/mongodb-community-server
    ports:
      - 27017:${MONGO_PORT}
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    networks:
      - back_net
    restart: unless-stopped

volumes:
  mongodb_data:
  chroma_data:
  ollama_data:

networks:
  back_net:
  front_net:
