@startuml "Diagrama componentes"

!theme mars

left to right direction

package "routers" {
    [auth_router]
    [conversation_router]
    [meeting_router] #LightBlue
    [settings_router]
}

package "services" {
    [auth_service]
    [conversation_service]
    [meeting_service] #LightBlue
    [settings_service]
}

package "repositories" as repositories {
    [auth_repository]
    [conversation_repository]
    [meeting_repository] #LightBlue
    [settings_repository]
}

database "Base de Datos" as DB

auth_router *-- auth_service
conversation_router *-- conversation_service
meeting_router *-- meeting_service
settings_router *-- settings_service

auth_service *-- auth_repository
conversation_service *-- conversation_repository
meeting_service *-- meeting_repository
settings_service *-- settings_repository

repositories -l-> DB

@enduml