@startuml Delete Meeting

title Delete Meeting

actor Client
participant "FastAPI Router" as Router
participant "Meeting Service" as Service
participant "Meeting Repository" as Repository

Client -> Router: DELETE /meetings/{id}

activate Router
Router -> Service: delete_meeting

activate Service
Service -> Repository: delete_meeting

activate Repository
Service <-- Repository
deactivate Repository

Router <-- Service
deactivate Service

Client <-- Router
deactivate Router

@enduml