@startuml Retrieve Meeting Summary

title Retrieve Meeting Summary

actor Client
participant "FastAPI Router" as Router
participant "Meeting Service" as Service
participant "Meeting Repository" as Repository

Client -> Router: Get /meetings/summary{id}

activate Router
Router -> Service: get_meeting_summary

activate Service
Service -> Repository: retrieve_meeting_summary

activate Repository
Service <-- Repository: meeting_summary
deactivate Repository

Router <-- Service: meeting_summary
deactivate Service

Client <-- Router: 200 OK + meeting_summary

@enduml