@startchen E/R

title E/R

entity MeetingMetadata {
    id: INTEGER <<key>>
    : STRING
    date: DATE
}
entity MeetingSummary {
    id: INTEGER <<key>>
    summary: STRING
}
entity MeetingTranscription {
    id: INTEGER <<key>>
    transcription: STRING
}
relationship Rel {
}

MeetingMetadata -1- Rel
MeetingSummary -1- Rel
MeetingTranscription -1- Rel

@endchen
